#-------Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: band_api
  labels:
    app: band_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: band_api
  template:
    metadata:
      labels:
        app: band_api
    spec:
      containers:
        - name: bandApiContainer
          image: localhost:6000/library/band_api:latest
          ports:
            - containerPort: 3000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: band-api-secret
                  key: postgres-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: band-api-secret
                  key: postgres-password
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: band-api-config
                  key: postgres-url
            - name: DB_URL_POSTGRES
              value: postgresql://$(USER_NAME):$(USER_PWD)@$(POSTGRES_URL):5432/band_api
#-----------------Secret
---
apiVersion: v1
kind: Service
metadata:
  name: band-api-service
spec:
  type: NodePort
  selector:
    app: band-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30440
#----------------------Confmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: band-api-config
data:
  postgres-url: postgres-service
---
#--------------------Secret
apiVersion: v1
kind: Secret
metadata:
  name: band-api-secret
type: Opaque
data:
  postgres-user: YWRtaW4=
  postgres-password: YWRtaW4xMjM=
